
topdir := ../..
builddir := $(topdir)/build
include $(builddir)/variables.mk
include $(builddir)/flags.mk

SUBDIRS = arch

include $(builddir)/deps.mk
include $(builddir)/rules.mk
include $(builddir)/targets.mk
