
HELLOWORLDDIR = helloworld
MINESWEEPERDIR = minesweeper

.PHONY = all clean

all:
	$(MAKE) -C $(HELLOWORLDDIR) all
	$(MAKE) -C $(MINESWEEPERDIR) all

clean:
	$(MAKE) -C $(HELLOWORLDDIR) clean
	$(MAKE) -C $(MINESWEEPERDIR) clean

