
topdir = ../../..
include ../../variables.mk
include ../../flags.mk

# include ../variables.mk
# include ../flags.mk

.PHONY = all clean

all:
	$(MAKE) -C $(target_cpu) all

clean:
	$(MAKE) -C $(target_cpu) clean

